/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelesApartar;

import ControlNavegacion.ControlAdmin;

/**
 *
 * @author HP
 */
public class ConfirmarApartado extends javax.swing.JPanel {
    private ControlAdmin control;
    /**
     * Creates new form ConfirmarApartado
     */
    public ConfirmarApartado(ControlAdmin control) {
        this.control = control;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelComputadora = new javax.swing.JLabel();
        labelApartadoPor1 = new javax.swing.JLabel();
        labelComputadora1 = new javax.swing.JLabel();
        BtnConfirmar = new javax.swing.JButton();
        BtnConfirmar1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelTitulo.setText("Resumen de Apartado");
        add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 19, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Unidad Academica:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 290, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Laboratorio:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 260, 60));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Tiempo de Apartado:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 270, 40));

        labelComputadora.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelComputadora.setText("Computadora:");
        add(labelComputadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, 270, 60));

        labelApartadoPor1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelApartadoPor1.setText("Apartado por:");
        add(labelApartadoPor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 270, 60));

        labelComputadora1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelComputadora1.setText("Lista de Softwares:");
        add(labelComputadora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 270, 90));

        BtnConfirmar.setBackground(new java.awt.Color(0, 0, 0));
        BtnConfirmar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        BtnConfirmar.setText("Confirmar");
        BtnConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnConfirmarMouseClicked(evt);
            }
        });
        add(BtnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 560, 120, 40));

        BtnConfirmar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnConfirmar1.setText("Cancelar");
        add(BtnConfirmar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 120, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnConfirmarMouseClicked
        // TODO add your handling code here:
        control.mostrarPantallaAdminisrador();
    }//GEN-LAST:event_BtnConfirmarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConfirmar;
    private javax.swing.JButton BtnConfirmar1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelApartadoPor1;
    private javax.swing.JLabel labelComputadora;
    private javax.swing.JLabel labelComputadora1;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
