/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelesApartar;

import ControlNavegacion.ControlAdmin;

/**
 *
 * @author HP
 */
public class SeleccionTiempoApartado extends javax.swing.JPanel {
    private ControlAdmin control;  
    /**
     * Creates new form SeleccionTiempoApartado
     */
    public SeleccionTiempoApartado(ControlAdmin control) {
        this.control = control;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelReloj = new javax.swing.JLabel();
        labelMinutos = new javax.swing.JLabel();
        BtnSubirMin = new javax.swing.JButton();
        labelMin = new javax.swing.JLabel();
        BtnBajarMin = new javax.swing.JButton();
        labelComputadora = new javax.swing.JLabel();
        labelSoftwares = new javax.swing.JLabel();
        BtnContinuar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelTitulo.setText("Selecciona el Tiempo de Uso");
        add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        labelReloj.setText("Aqui pondre la imagen del reloj ");
        add(labelReloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 190, 170));

        labelMinutos.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelMinutos.setText("60");
        add(labelMinutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 80, -1));

        BtnSubirMin.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        BtnSubirMin.setText("+");
        BtnSubirMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSubirMinActionPerformed(evt);
            }
        });
        add(BtnSubirMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 40, 40));

        labelMin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelMin.setText("Minutos");
        add(labelMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        BtnBajarMin.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        BtnBajarMin.setText("-");
        BtnBajarMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBajarMinActionPerformed(evt);
            }
        });
        add(BtnBajarMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 40, 40));

        labelComputadora.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelComputadora.setText("Computadora 01");
        add(labelComputadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 250, 30));

        labelSoftwares.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelSoftwares.setText("Lista de Softwares: ");
        add(labelSoftwares, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 250, 80));

        BtnContinuar.setBackground(new java.awt.Color(0, 0, 0));
        BtnContinuar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        BtnContinuar.setText("Continuar");
        BtnContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnContinuarMouseClicked(evt);
            }
        });
        add(BtnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, 110, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSubirMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSubirMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSubirMinActionPerformed

    private void BtnBajarMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBajarMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBajarMinActionPerformed

    private void BtnContinuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnContinuarMouseClicked
        // TODO add your handling code here:
        control.mostrarPantallaConfirmarApartado();
    }//GEN-LAST:event_BtnContinuarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBajarMin;
    private javax.swing.JButton BtnContinuar;
    private javax.swing.JButton BtnSubirMin;
    private javax.swing.JLabel labelComputadora;
    private javax.swing.JLabel labelMin;
    private javax.swing.JLabel labelMinutos;
    private javax.swing.JLabel labelReloj;
    private javax.swing.JLabel labelSoftwares;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
