/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelesApartar;

import ControlNavegacion.ControlFlujoApartar;
import DTOs.AgregarComputadoraDTO;
import Interfacez.IComputadoraBO;
import entidades.ComputadoraDominio;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class SeleccionComputadora extends javax.swing.JPanel {
    private ControlFlujoApartar control;
    private IComputadoraBO compBO;
    private AgregarComputadoraDTO computadoraActual;
    /**
     * Creates new form SeleccionComputadora
     */
    public SeleccionComputadora(IComputadoraBO compBO,ControlFlujoApartar control) {
        initComponents();
        this.control = control;
        this.compBO=compBO;
        this.lblLab.setText("Laboratorio: "+control.getLaboratorioActual().getNombreLaboratorio());
        tblComputadoras.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                if (evt.getClickCount() == 2 && !evt.isConsumed()) {
                    evt.consume();
                    int fila = tblComputadoras.rowAtPoint(evt.getPoint());
                    if (fila != -1) {
                        String numeroComputadora = tblComputadoras.getValueAt(fila, 0).toString();
                        JOptionPane.showMessageDialog(btnContinuar, "Computadora Seleccionada: "+numeroComputadora, "Computadora", JOptionPane.INFORMATION_MESSAGE);
                        computadoraActual = new AgregarComputadoraDTO();
                        computadoraActual.setNumero(numeroComputadora);
                        control.mostrarPantallaTiempoApartado();
                    }
                }
            }
        });
        llenarTabla();
        
    }
    
    private void llenarTabla(){
        
        DefaultTableModel modelo = (DefaultTableModel) this.tblComputadoras.getModel();
        modelo.setRowCount(0);
        
        System.out.println(control.getLaboratorioActual().getId());
        for(ComputadoraDominio c : compBO.consultarComputadorasPorLaboratorio(control.getLaboratorioActual())){
            modelo.addRow(new Object[]{
                c.getNumeroComputadora()   
            });
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        lblLab = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblComputadoras = new javax.swing.JTable();
        btnContinuar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelTitulo.setText("Computadoras");
        add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        lblLab.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLab.setText("Laboratorio: ");
        add(lblLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 220, -1));

        tblComputadoras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Numero"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblComputadoras);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 440, -1));

        btnContinuar.setText("Continuar");
        btnContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnContinuarMouseClicked(evt);
            }
        });
        add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 580, 100, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContinuarMouseClicked
        // TODO add your handling code here:
        //control.mostrarPantallaTiempoApartado();
    }//GEN-LAST:event_btnContinuarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel lblLab;
    private javax.swing.JTable tblComputadoras;
    // End of variables declaration//GEN-END:variables
}
