/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelesApartar;

import ControlNavegacion.ControlFlujoApartar;
import DTOs.AgregarLaboratorioDTO;
import DTOs.LaboratorioDTO;
import Interfacez.ILaboratorioBO;
import entidades.LaboratorioDominio;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author HP
 */
public class SeleccionLaboratorio extends javax.swing.JPanel {
    private ControlFlujoApartar control;
    private ILaboratorioBO labBO;
    private AgregarLaboratorioDTO laboratorioActual;
    
    
    /**
     * Creates new form SeleccionLaboratorio
     */
    public SeleccionLaboratorio(ILaboratorioBO labBO,ControlFlujoApartar control) {
        initComponents();
        this.control = control;
        this.labBO=labBO;
        tblLaboratorios.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                if (evt.getClickCount() == 2 && !evt.isConsumed()) {
                    evt.consume();
                    int fila = tblLaboratorios.rowAtPoint(evt.getPoint());
                    if (fila != -1) {
                        String nombreLaboratorio = tblLaboratorios.getValueAt(fila, 0).toString();
                        JOptionPane.showMessageDialog(BtnContinuar, "Laboratorio Seleccionado: "+nombreLaboratorio, "Laboratorio", JOptionPane.INFORMATION_MESSAGE);
                        laboratorioActual = new AgregarLaboratorioDTO(nombreLaboratorio);
                        control.mostrarPantallaSeleccionComputadora();
                    }
                }
            }
        });
        llenarTabla();
        
    }
    
    private void llenarTabla(){
        DefaultTableModel modelo = (DefaultTableModel) this.tblLaboratorios.getModel();
        modelo.setRowCount(0);
        
        for(LaboratorioDominio l : labBO.consultarLaboratoriosUnidadAcademica(1L)){
            modelo.addRow(new Object[]{
                l.getNombreLaboratorio()
            });
        }
    }

    public AgregarLaboratorioDTO getLaboratorioActual() {
        return laboratorioActual;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblLaboratorios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        BtnContinuar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblLaboratorios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblLaboratorios);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 520, 420));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Laboratorios");
        jLabel1.setToolTipText("");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 200, 60));

        BtnContinuar.setText("Continuar");
        BtnContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnContinuarMouseClicked(evt);
            }
        });
        BtnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnContinuarActionPerformed(evt);
            }
        });
        add(BtnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 570, 100, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("--Doble click para seleccionar un laboratorio--");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnContinuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnContinuarMouseClicked
        // TODO add your handling code here:
//        control.mostrarPantallaSeleccionComputadora();
    }//GEN-LAST:event_BtnContinuarMouseClicked

    private void BtnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnContinuarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BtnContinuarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnContinuar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLaboratorios;
    // End of variables declaration//GEN-END:variables
}
