/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelesApartar;

import ControlNavegacion.ControlLoginAlumno;
import DTOs.LaboratorioDTO;
import Interfacez.ILaboratorioBO;
import entidades.LaboratorioDominio;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author HP
 */
public class SeleccionLaboratorio extends javax.swing.JPanel {
    private ControlLoginAlumno control;
    private ILaboratorioBO labBO;
    /**
     * Creates new form SeleccionLaboratorio
     */
    public SeleccionLaboratorio(ILaboratorioBO labBO,ControlLoginAlumno control) {
        initComponents();
        this.control = control;
        this.labBO=labBO;
        llenarTabla();
        
    }
    
    private void llenarTabla(){
        DefaultTableModel modelo = (DefaultTableModel) this.tblLaboratorios.getModel();
        modelo.setRowCount(0);
        
        for(LaboratorioDominio l : labBO.consultarLaboratoriosUnidadAcademica(1L)){
            modelo.addRow(new Object[]{
                l.getNombreLaboratorio()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblLaboratorios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        BtnContinuar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblLaboratorios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nombre"
            }
        ));
        jScrollPane1.setViewportView(tblLaboratorios);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 520, 460));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Laboratorios");
        jLabel1.setToolTipText("");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 200, 60));

        BtnContinuar.setText("Continuar");
        BtnContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnContinuarMouseClicked(evt);
            }
        });
        add(BtnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 570, 100, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnContinuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnContinuarMouseClicked
        // TODO add your handling code here:
//        control.mostrarPantallaSeleccionComputadora();
    }//GEN-LAST:event_BtnContinuarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnContinuar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLaboratorios;
    // End of variables declaration//GEN-END:variables
}
