/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelesAdministrador;

import ControlNavegacion.ControlAdmin;
import DAOs.LaboratorioDAO;
import javax.swing.JFileChooser;
import reportes.PDFCentroComputo;
import entidades.LaboratorioDominio;
import java.util.List;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author HP
 */
public class ListadoLaboratoriosAdmin extends javax.swing.JPanel {
    private ControlAdmin control;
    /**
     * Creates new form ListaComputadorasAdmin
     */
    public ListadoLaboratoriosAdmin(ControlAdmin control) {
        this.control = control;
        
        initComponents();
        valoresDefault();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaLaboratorios = new javax.swing.JTable();
        BtnAtrasPagina = new javax.swing.JButton();
        BtnSIgPagina = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        BtnAgregar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnCerrarSesion = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        labelFiltros = new javax.swing.JLabel();
        labelFiltroLaboratorio = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnGenerarReporte = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaLaboratorios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Unidad Academica", "ID Laboratorio", "nombre", "Horario"
            }
        ));
        jScrollPane1.setViewportView(tablaLaboratorios);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 1010, 330));

        BtnAtrasPagina.setText("<---");
        BtnAtrasPagina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAtrasPaginaMouseClicked(evt);
            }
        });
        add(BtnAtrasPagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, 20));

        BtnSIgPagina.setText("--->");
        BtnSIgPagina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSIgPaginaMouseClicked(evt);
            }
        });
        add(BtnSIgPagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 500, -1, -1));

        BtnEditar.setBackground(new java.awt.Color(0, 0, 0));
        BtnEditar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnEditar.setForeground(new java.awt.Color(255, 255, 255));
        BtnEditar.setText("Editar");
        add(BtnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, 120, 40));

        BtnAgregar.setBackground(new java.awt.Color(0, 0, 0));
        BtnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgregar.setText("Agregar");
        BtnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAgregarMouseClicked(evt);
            }
        });
        add(BtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, 120, 40));

        BtnEliminar.setBackground(new java.awt.Color(0, 0, 0));
        BtnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        BtnEliminar.setText("Eliminar");
        BtnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEliminarMouseClicked(evt);
            }
        });
        add(BtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 520, 120, 40));

        BtnCerrarSesion.setBackground(new java.awt.Color(0, 0, 0));
        BtnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        BtnCerrarSesion.setText("Cerrar Sesion");
        BtnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCerrarSesionMouseClicked(evt);
            }
        });
        add(BtnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 140, 40));

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelTitulo.setText("Listado Laboratorios");
        add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        labelFiltros.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelFiltros.setText("Filtros:");
        add(labelFiltros, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        labelFiltroLaboratorio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelFiltroLaboratorio.setText("Laboratorio");
        add(labelFiltroLaboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 100, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unidad Nainari", "Unidad Centro" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 20, 30));

        btnGenerarReporte.setBackground(new java.awt.Color(0, 0, 0));
        btnGenerarReporte.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGenerarReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarReporte.setText("Generar reporte de laboratorios");
        btnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteActionPerformed(evt);
            }
        });
        add(btnGenerarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, 290, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAtrasPaginaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAtrasPaginaMouseClicked
        // TODO add your handling code here:
        //
    }//GEN-LAST:event_BtnAtrasPaginaMouseClicked

    private void BtnSIgPaginaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSIgPaginaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSIgPaginaMouseClicked

    private void BtnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAgregarMouseClicked
        // TODO add your handling code here:
        control.mostrarPantallaFormularioLaboratorio();
    }//GEN-LAST:event_BtnAgregarMouseClicked

    private void BtnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEliminarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEliminarMouseClicked

    private void BtnCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCerrarSesionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCerrarSesionMouseClicked

    private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarReporteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnAtrasPagina;
    private javax.swing.JButton BtnCerrarSesion;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnSIgPagina;
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelFiltroLaboratorio;
    private javax.swing.JLabel labelFiltros;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTable tablaLaboratorios;
    // End of variables declaration//GEN-END:variables

    
     public void cargarTabla(){
        DefaultTableModel modeloTabla = (DefaultTableModel) tablaLaboratorios.getModel();
        modeloTabla.setRowCount(0); 
        for(LaboratorioDominio lab : control.cargarLaboratrios()){
            modeloTabla.addRow(new Object[]{
                lab.getUnidadAcademica().getNombreUnidad(),
                lab.getId(),
                lab.getNombreLaboratorio(),
                (lab.getHoraInicio().toString()+ "-"+ lab.getHoraFin().toString())
                
            });
        }
     }
    public void valoresDefault(){
        setSize(1030, 620);
        setVisible(true);
    }

}
