/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelesAdministrador;

import ControlNavegacion.ControlNavegacion;

/**
 *
 * @author HP
 */
public class ListadoBloqueos extends javax.swing.JPanel {
    ControlNavegacion control;
    /**
     * Creates new form ListaComputadorasAdmin
     */
    public ListadoBloqueos(ControlNavegacion control) {
        this.control = control;
        valoresDefault();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtnAtrasPagina = new javax.swing.JButton();
        BtnSIgPagina = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        BtnAgregar = new javax.swing.JButton();
        BtnCerrarSesion = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        labelFiltros = new javax.swing.JLabel();
        labelFiltroLaboratorio = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        BtnSalir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Alumno", "Nombre Alumno", "Bloqueado Por"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 710, 330));

        BtnAtrasPagina.setText("<---");
        BtnAtrasPagina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAtrasPaginaMouseClicked(evt);
            }
        });
        add(BtnAtrasPagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, 20));

        BtnSIgPagina.setText("--->");
        BtnSIgPagina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSIgPaginaMouseClicked(evt);
            }
        });
        add(BtnSIgPagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 500, -1, -1));

        BtnEditar.setBackground(new java.awt.Color(0, 0, 0));
        BtnEditar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnEditar.setForeground(new java.awt.Color(255, 255, 255));
        BtnEditar.setText("Desbloquear alumno");
        add(BtnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, -1, 40));

        BtnAgregar.setBackground(new java.awt.Color(0, 0, 0));
        BtnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgregar.setText("Nuevo Bloqueo");
        BtnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAgregarMouseClicked(evt);
            }
        });
        add(BtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, 160, 40));

        BtnCerrarSesion.setBackground(new java.awt.Color(0, 0, 0));
        BtnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        BtnCerrarSesion.setText("Cerrar Sesion");
        BtnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCerrarSesionMouseClicked(evt);
            }
        });
        add(BtnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 140, 40));

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelTitulo.setText("Listado Bloqueos");
        add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        labelFiltros.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelFiltros.setText("Filtros:");
        add(labelFiltros, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        labelFiltroLaboratorio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelFiltroLaboratorio.setText("Administrador");
        add(labelFiltroLaboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 130, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unidad Nainari", "Unidad Centro" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 20, 30));

        BtnSalir.setBackground(new java.awt.Color(0, 0, 0));
        BtnSalir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnSalir.setForeground(new java.awt.Color(255, 255, 255));
        BtnSalir.setText("Salir");
        BtnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSalirMouseClicked(evt);
            }
        });
        add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, 120, 40));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Generar reporte");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, -1, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAtrasPaginaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAtrasPaginaMouseClicked
        // TODO add your handling code here:
        //
    }//GEN-LAST:event_BtnAtrasPaginaMouseClicked

    private void BtnSIgPaginaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSIgPaginaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSIgPaginaMouseClicked

    private void BtnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAgregarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAgregarMouseClicked

    private void BtnCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCerrarSesionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCerrarSesionMouseClicked

    private void BtnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSalirMouseClicked
        // TODO add your handling code here:
        control.mostrarPantallaAdminisrador();
    }//GEN-LAST:event_BtnSalirMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnAtrasPagina;
    private javax.swing.JButton BtnCerrarSesion;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnSIgPagina;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelFiltroLaboratorio;
    private javax.swing.JLabel labelFiltros;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables

//    public ArrayList<String> cargarUnidadesAcademicas(){
//       //control.cargarUnidadesAcademicas(); sin filtros aun
//       ArrayList<String> listaUnidades = new ArrayList<>();
//       listaUnidades.set(1, "Unidada Nainari");
//       return 
//    }
    //creo q no se ocupa aun
   // public ArrayList<String>
    public void valoresDefault(){
        setSize(1040, 620);
        setVisible(true);
    }

}
