/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PanelesAdministrador;

import DAOs.BloqueoDAO;
import DAOs.CarreraDAO;
import DAOs.LaboratorioDAO;
import entidades.BloqueoDominio;
import entidades.CarreraDominio;
import entidades.LaboratorioDominio;

import ControlNavegacion.ControlAdmin;

import java.awt.BorderLayout;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import reportes.PDFBloqueos;
import reportes.PDFCarreras;
import reportes.PDFCentroComputo;

/**
 *
 * @author HP
 */
public class MenuAdministrador extends javax.swing.JFrame {
    ControlAdmin control;
   /**
     * Creates new form MenuAdministrador
     */
    public MenuAdministrador(ControlAdmin control) {
        this.control = control;
        valoresDefault();
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenidoActual = new javax.swing.JPanel();
        menuBarAdmin = new javax.swing.JMenuBar();
        Laboratorios = new javax.swing.JMenu();
        listadoLaboratorios = new javax.swing.JMenuItem();
        menuAgregarLaboratorio = new javax.swing.JMenuItem();
        menuEditarLaboratorio = new javax.swing.JMenuItem();
        ListadoComputadoras = new javax.swing.JMenu();
        listadoComputadoras = new javax.swing.JMenuItem();
        agregarComputadora = new javax.swing.JMenuItem();
        bloqueo = new javax.swing.JMenu();
        ListadoBloqueos = new javax.swing.JMenuItem();
        menuAgregarBloqueo = new javax.swing.JMenuItem();
        menuDesbloquearAlumno = new javax.swing.JMenuItem();
        menuConfiguracion = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        menuCarreras = new javax.swing.JMenuItem();
        menuCentroComputo = new javax.swing.JMenuItem();
        menuBloqueos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenidoActual.setMaximumSize(new java.awt.Dimension(1050, 620));
        contenidoActual.setLayout(new java.awt.BorderLayout());
        getContentPane().add(contenidoActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1030, 620));

        Laboratorios.setText("Laboratorios");

        listadoLaboratorios.setText("Lista de Laboratorios");
        listadoLaboratorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listadoLaboratoriosActionPerformed(evt);
            }
        });
        Laboratorios.add(listadoLaboratorios);

        menuAgregarLaboratorio.setText("Agregar laboratorio");
        menuAgregarLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgregarLaboratorioActionPerformed(evt);
            }
        });
        Laboratorios.add(menuAgregarLaboratorio);

        menuEditarLaboratorio.setText("EditarLaboratorio");
        Laboratorios.add(menuEditarLaboratorio);

        menuBarAdmin.add(Laboratorios);

        ListadoComputadoras.setText("Computadoras");

        listadoComputadoras.setText("Lista de Computadoras");
        listadoComputadoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listadoComputadorasActionPerformed(evt);
            }
        });
        ListadoComputadoras.add(listadoComputadoras);

        agregarComputadora.setText("Agregar Computadora");
        agregarComputadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarComputadoraActionPerformed(evt);
            }
        });
        ListadoComputadoras.add(agregarComputadora);

        menuBarAdmin.add(ListadoComputadoras);

        bloqueo.setText("Bloqueo");

        ListadoBloqueos.setText("Listado Bloqueos");
        ListadoBloqueos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListadoBloqueosActionPerformed(evt);
            }
        });
        bloqueo.add(ListadoBloqueos);

        menuAgregarBloqueo.setText("Agregar bloqueo");
        bloqueo.add(menuAgregarBloqueo);

        menuDesbloquearAlumno.setText("Desbloquear alumno");
        bloqueo.add(menuDesbloquearAlumno);

        menuBarAdmin.add(bloqueo);

        menuConfiguracion.setText("Configuracion");
        menuConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConfiguracionActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Cerrar Sesion");
        menuConfiguracion.add(jMenuItem1);

        menuBarAdmin.add(menuConfiguracion);

        menuReportes.setText("Reportes");

        menuCarreras.setText("Carreras");
        menuCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCarrerasActionPerformed(evt);
            }
        });
        menuReportes.add(menuCarreras);

        menuCentroComputo.setText("Centro computo");
        menuCentroComputo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCentroComputoActionPerformed(evt);
            }
        });
        menuReportes.add(menuCentroComputo);

        menuBloqueos.setText("Bloqueos");
        menuBloqueos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBloqueosActionPerformed(evt);
            }
        });
        menuReportes.add(menuBloqueos);

        menuBarAdmin.add(menuReportes);

        setJMenuBar(menuBarAdmin);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAgregarLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgregarLaboratorioActionPerformed
        control.mostrarPantallaSeleccionarUnidad();
// TODO add your handling code here:
    }//GEN-LAST:event_menuAgregarLaboratorioActionPerformed

    private void listadoLaboratoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listadoLaboratoriosActionPerformed
        // TODO add your handling code here:
        control.mostrarListadoLaboratoriosAdmin();
    }//GEN-LAST:event_listadoLaboratoriosActionPerformed

    private void ListadoBloqueosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListadoBloqueosActionPerformed
        // TODO add your handling code here:
        control.mostrarPantallaBloqueosAdmin();
    }//GEN-LAST:event_ListadoBloqueosActionPerformed

    private void listadoComputadorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listadoComputadorasActionPerformed

        // TODO add your handling code here:
        
        control.mostrarListadoComputadorasAdmin();
    }//GEN-LAST:event_listadoComputadorasActionPerformed

    private void menuConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConfiguracionActionPerformed
        // TODO add your handling code here:
//        control.iniciarSistema();
    }//GEN-LAST:event_menuConfiguracionActionPerformed

    private void menuCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCarrerasActionPerformed
    try {
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Guardar reporte de carreras...");
    int userSelection = fileChooser.showSaveDialog(this);

    if (userSelection == JFileChooser.APPROVE_OPTION) {
        String ruta = fileChooser.getSelectedFile().getAbsolutePath();

        CarreraDAO carreraDAO = CarreraDAO.getInstanciaDAO();
        List<CarreraDominio> carreras = carreraDAO.consultarCarreras();

        PDFCarreras reporte = new PDFCarreras();
        reporte.generarReporte(ruta.endsWith(".pdf") ? ruta : ruta + ".pdf");

        javax.swing.JOptionPane.showMessageDialog(this, "Reporte de carreras generado con éxito.");
    }
} catch (Exception ex) {
    ex.printStackTrace();
    javax.swing.JOptionPane.showMessageDialog(this, "Error al generar el reporte:\n" + ex.getMessage(),
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
}

// TODO add your handling code here:
    }//GEN-LAST:event_menuCarrerasActionPerformed

    private void menuCentroComputoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCentroComputoActionPerformed
    try {
        // Seleccionar la ruta para guardar el PDF
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar reporte como...");
        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            String ruta = fileChooser.getSelectedFile().getAbsolutePath();

            // Obtener los datos
            LaboratorioDAO laboratorioDAO = LaboratorioDAO.getInstanciaDAO();
            List<LaboratorioDominio> laboratorios = laboratorioDAO.consultarLaboratorios();

            // Crear el reporte
            PDFCentroComputo reporte = new PDFCentroComputo();
            reporte.setLaboratoriosReporte(laboratorios);
            reporte.generarReporte(ruta.endsWith(".pdf") ? ruta : ruta + ".pdf");

            javax.swing.JOptionPane.showMessageDialog(this, "Reporte generado con éxito.");
        }
    } catch (Exception ex) {
        ex.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al generar el reporte:\n" + ex.getMessage(),
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
// TODO add your handling code here:
    }//GEN-LAST:event_menuCentroComputoActionPerformed

    private void menuBloqueosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBloqueosActionPerformed
    try {
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Guardar reporte de bloqueos...");
    int userSelection = fileChooser.showSaveDialog(this);

    if (userSelection == JFileChooser.APPROVE_OPTION) {
        String ruta = fileChooser.getSelectedFile().getAbsolutePath();

        BloqueoDAO bloqueoDAO = BloqueoDAO.getInstanciaDAO();
        List<BloqueoDominio> bloqueos = bloqueoDAO.consultarBloqueos();

        PDFBloqueos reporte = new PDFBloqueos();
        reporte.generarReporte(ruta.endsWith(".pdf") ? ruta : ruta + ".pdf");

        javax.swing.JOptionPane.showMessageDialog(this, "Reporte de bloqueos generado con éxito.");
    }
} catch (Exception ex) {
    ex.printStackTrace();
    javax.swing.JOptionPane.showMessageDialog(this, "Error al generar el reporte:\n" + ex.getMessage(),
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
}

// TODO add your handling code here:
    }//GEN-LAST:event_menuBloqueosActionPerformed

    private void agregarComputadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarComputadoraActionPerformed
        // TODO add your handling code here:
        control.mostrarPantallaAgregarComputadora();
    }//GEN-LAST:event_agregarComputadoraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Laboratorios;
    private javax.swing.JMenuItem ListadoBloqueos;
    private javax.swing.JMenu ListadoComputadoras;
    private javax.swing.JMenuItem agregarComputadora;
    private javax.swing.JMenu bloqueo;
    private javax.swing.JPanel contenidoActual;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem listadoComputadoras;
    private javax.swing.JMenuItem listadoLaboratorios;
    private javax.swing.JMenuItem menuAgregarBloqueo;
    private javax.swing.JMenuItem menuAgregarLaboratorio;
    private javax.swing.JMenuBar menuBarAdmin;
    private javax.swing.JMenuItem menuBloqueos;
    private javax.swing.JMenuItem menuCarreras;
    private javax.swing.JMenuItem menuCentroComputo;
    private javax.swing.JMenu menuConfiguracion;
    private javax.swing.JMenuItem menuDesbloquearAlumno;
    private javax.swing.JMenuItem menuEditarLaboratorio;
    private javax.swing.JMenu menuReportes;
    // End of variables declaration//GEN-END:variables
    
    public void valoresDefault(){
        setTitle("Menu Administrador");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setSize(1040, 650);
    }
    
    public void cambiarPanel(JPanel panel){
        contenidoActual.removeAll();
        contenidoActual.add(panel, BorderLayout.CENTER);
        contenidoActual.revalidate();
        contenidoActual.repaint();
    }

}
