/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PanelesAdministrador;

import ControlNavegacion.ControlNavegacion;

/**
 *
 * @author HP
 */
public class MenuAdministrador extends javax.swing.JFrame {
    ControlNavegacion control;
   /**
     * Creates new form MenuAdministrador
     */
    public MenuAdministrador(ControlNavegacion control) {
        this.control = control;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBarAdmin = new javax.swing.JMenuBar();
        laboratorios = new javax.swing.JMenu();
        menuListaLab = new javax.swing.JMenuItem();
        menuAgregarLaboratorio = new javax.swing.JMenuItem();
        menuEditarLaboratorio = new javax.swing.JMenuItem();
        computadoras = new javax.swing.JMenu();
        menuListaPCs = new javax.swing.JMenuItem();
        bloqueo = new javax.swing.JMenu();
        menuListaBloqueos = new javax.swing.JMenuItem();
        menuAgregarBloqueo = new javax.swing.JMenuItem();
        menuDesbloquearAlumno = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        laboratorios.setText("Laboratorios");

        menuListaLab.setText("Lista de Laboratorios");
        menuListaLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuListaLabMouseClicked(evt);
            }
        });
        menuListaLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListaLabActionPerformed(evt);
            }
        });
        laboratorios.add(menuListaLab);

        menuAgregarLaboratorio.setText("Agregar laboratorio");
        menuAgregarLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgregarLaboratorioActionPerformed(evt);
            }
        });
        laboratorios.add(menuAgregarLaboratorio);

        menuEditarLaboratorio.setText("menuEditarLaboratorio");
        laboratorios.add(menuEditarLaboratorio);

        menuBarAdmin.add(laboratorios);

        computadoras.setText("Computadoras");

        menuListaPCs.setText("Lista de Computadoras");
        menuListaPCs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuListaPCsMouseClicked(evt);
            }
        });
        computadoras.add(menuListaPCs);

        menuBarAdmin.add(computadoras);

        bloqueo.setText("Bloqueo");

        menuListaBloqueos.setText("Registro de bloqueos");
        bloqueo.add(menuListaBloqueos);

        menuAgregarBloqueo.setText("Agregar bloqueo");
        bloqueo.add(menuAgregarBloqueo);

        menuDesbloquearAlumno.setText("Desbloquear alumno");
        bloqueo.add(menuDesbloquearAlumno);

        menuBarAdmin.add(bloqueo);

        setJMenuBar(menuBarAdmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuListaPCsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuListaPCsMouseClicked
        // TODO add your handling code here:
        //llamar a Metodo en control para mostrar la pantalla de listaLaboratorio, tendra que ser diferente a la que esta en el package Paneles
        //(crear nuevo panel en este package para mostrar la lista con los botones Agregar, editar, eliminar
    }//GEN-LAST:event_menuListaPCsMouseClicked

    private void menuListaLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuListaLabMouseClicked
        // TODO add your handling code here:
        //lo mismo de arriba la vdd
    }//GEN-LAST:event_menuListaLabMouseClicked

    private void menuAgregarLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgregarLaboratorioActionPerformed
        control.mostrarPantallaAgregarLaboratorio();
// TODO add your handling code here:
    }//GEN-LAST:event_menuAgregarLaboratorioActionPerformed

    private void menuListaLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListaLabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuListaLabActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu bloqueo;
    private javax.swing.JMenu computadoras;
    private javax.swing.JMenu laboratorios;
    private javax.swing.JMenuItem menuAgregarBloqueo;
    private javax.swing.JMenuItem menuAgregarLaboratorio;
    private javax.swing.JMenuBar menuBarAdmin;
    private javax.swing.JMenuItem menuDesbloquearAlumno;
    private javax.swing.JMenuItem menuEditarLaboratorio;
    private javax.swing.JMenuItem menuListaBloqueos;
    private javax.swing.JMenuItem menuListaLab;
    private javax.swing.JMenuItem menuListaPCs;
    // End of variables declaration//GEN-END:variables
}
