/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelesAdministrador;

import ControlNavegacion.ControlAdmin;
import entidades.UnidadAcademicaDominio;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author HP
 */
public class SeleccionarUnidad extends javax.swing.JPanel {
    private ControlAdmin control;
    private UnidadAcademicaDominio unidadTemporal;
    
    
    /**
     * Creates new form SeleccionarUnidad
     */
    public SeleccionarUnidad(ControlAdmin control) {
        this.control = control;
        initComponents();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTItulo = new javax.swing.JLabel();
        labelSubtitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUnidades = new javax.swing.JTable();
        BtnCancelar = new javax.swing.JButton();
        BtnContinuar = new javax.swing.JButton();
        BtnAtras = new javax.swing.JButton();
        BtnSig = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTItulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelTItulo.setText("Agregar Laboratorio");
        add(labelTItulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 370, 91));

        labelSubtitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelSubtitulo.setText("Seleccione la Unidad para el Laboratorio");
        add(labelSubtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 450, 60));

        tablaUnidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nombre"
            }
        ));
        tablaUnidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUnidadesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUnidades);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 440, 380));

        BtnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCancelarMouseClicked(evt);
            }
        });
        add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 100, 40));

        BtnContinuar.setBackground(new java.awt.Color(0, 0, 0));
        BtnContinuar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        BtnContinuar.setText("Continuar");
        BtnContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnContinuarMouseClicked(evt);
            }
        });
        add(BtnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 560, 120, 40));

        BtnAtras.setText("atras");
        BtnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAtrasMouseClicked(evt);
            }
        });
        add(BtnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, -1, -1));

        BtnSig.setText("Siguiente");
        BtnSig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSigMouseClicked(evt);
            }
        });
        add(BtnSig, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 560, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCancelarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCancelarMouseClicked

    private void BtnContinuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnContinuarMouseClicked
        // TODO add your handling code here:
        control.mostrarPantallaFormularioLaboratorio();
    }//GEN-LAST:event_BtnContinuarMouseClicked

    private void BtnSigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSigMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSigMouseClicked

    private void BtnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAtrasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAtrasMouseClicked

    private void tablaUnidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUnidadesMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            int filaSeleccionada = tablaUnidades.getSelectedRow();
            //para cuando agregue el filtro
            int filaModelo = tablaUnidades.convertRowIndexToModel(filaSeleccionada);
            unidadTemporal = control.cargarUnidadesAcademicas().get(filaModelo);
            setUnidadAcademica();
        }
        System.out.println("unidad Seleccionada:  " + unidadTemporal.getNombreUnidad());
    }//GEN-LAST:event_tablaUnidadesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtras;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnContinuar;
    private javax.swing.JButton BtnSig;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelSubtitulo;
    private javax.swing.JLabel labelTItulo;
    private javax.swing.JTable tablaUnidades;
    // End of variables declaration//GEN-END:variables

    public void cargarTabla(){
        DefaultTableModel modeloTabla = (DefaultTableModel) tablaUnidades.getModel();
        modeloTabla.setRowCount(0); 
        int cont1 = 1;
        int cont2 = 1;
        for(UnidadAcademicaDominio unidad : control.cargarUnidadesAcademicas()){
            modeloTabla.addRow(new Object[]{
                unidad.getId(),
                unidad.getNombreUnidad(),
                
            });
        }
        
    }
    public void setUnidadAcademica(){
        control.setUnidadAcademica(unidadTemporal);
        control.setUnidadLab(unidadTemporal.getNombreUnidad());
    }
}
