/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

import ControlNavegacion.ControlAdmin;
import entidades.LaboratorioDominio;
import entidades.UnidadAcademicaDominio;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Sandra
 */
public class AgregarComputadora extends javax.swing.JPanel {
    private ControlAdmin control;
    /**
     * Creates new form AgregarComputadora
     */
    public AgregarComputadora(ControlAdmin control) {
        this.control = control;
        initComponents();
        valoresDefault();
        listenerComboUnidad();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboBoxUnidad = new javax.swing.JComboBox<>();
        comboBoxLaboratorio = new javax.swing.JComboBox<>();
        comboBoxTipoPC = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Agregar computadora");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 19, -1, -1));

        comboBoxUnidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxUnidadActionPerformed(evt);
            }
        });
        add(comboBoxUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 99, -1, -1));

        comboBoxLaboratorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboBoxLaboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 152, -1, -1));

        comboBoxTipoPC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alumno", "Portero", "Administrador", " " }));
        add(comboBoxTipoPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 203, -1, -1));

        jLabel2.setText("Seleccione una unidad academica");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 102, -1, -1));

        jLabel3.setText("Seleccione un laboratorio");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 155, -1, -1));

        jLabel4.setText("Seleccione el tipo de computadora");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 206, -1, -1));

        btnContinuar.setText("Continuar");
        add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 271, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxUnidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxUnidadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JComboBox<String> comboBoxLaboratorio;
    private javax.swing.JComboBox<String> comboBoxTipoPC;
    private javax.swing.JComboBox<String> comboBoxUnidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    private void valoresDefault(){
        DefaultComboBoxModel modeloUnidad = new DefaultComboBoxModel();
         for(UnidadAcademicaDominio lab : control.cargarUnidadesAcademicas()){
            modeloUnidad. addElement(new Object[]{
                lab.getNombreUnidad()
            });
            comboBoxUnidad.setModel(modeloUnidad);
        }
//         listenerComboUnidad();
     }
    
    public void actualizarComboLaboratorio(List<UnidadAcademicaDominio> listaUnidades){
        
    }
    public void listenerComboUnidad(){
        comboBoxUnidad.addActionListener(e -> {
            UnidadAcademicaDominio seleccionada = (UnidadAcademicaDominio) comboBoxUnidad.getSelectedItem();

            if (seleccionada != null) {
                // Consulta los laboratorios de esa unidad
                List<LaboratorioDominio> laboratorios = control.consultarLaboratoriosUnidadAcademica(seleccionada.getId());

                // Actualiza el segundo combo
                DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
                for (LaboratorioDominio lab : laboratorios) {
                    modelo.addElement(lab.getNombreLaboratorio());
                }
                comboBoxLaboratorio.setModel(modelo);
            }
        });
            }
}
