/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

/**
 *
 * @author Sandra
 */
public class AgregarComputadoraNumero extends javax.swing.JPanel {

    /**
     * Creates new form AgregarComputadoraNumero
     */
    public AgregarComputadoraNumero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaComputadoras = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        txtNumeroComputadora = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("AgregarComputadora");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 14, -1, -1));

        listaComputadoras.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaComputadoras);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 134, 96, -1));

        jLabel2.setText("Asigne un numero de computadora");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 135, 201, 25));
        jLabel2.getAccessibleContext().setAccessibleName("Asigne un numero de \ncomputadora");

        add(txtNumeroComputadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 166, -1, -1));

        jLabel3.setText("Lista computadoras");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 106, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaComputadoras;
    private javax.swing.JTextField txtNumeroComputadora;
    // End of variables declaration//GEN-END:variables
}
