/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

import ControlNavegacion.ControlNavegacion;

/**
 *
 * @author Sandra
 */
public class AgregarLaboratorio extends javax.swing.JPanel {
    ControlNavegacion control;

    /**
     * Creates new form AgregarLaboratorio
     */
    public AgregarLaboratorio() {
        initComponents();
    }
    public AgregarLaboratorio(ControlNavegacion control) {
        this.control = control;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        spinnerHora = new javax.swing.JSpinner();
        spinnerMinuto = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Agregar laboratorio");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setText("Nombre");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 109, -1, -1));
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 131, 139, -1));

        jLabel3.setText("Horario");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        add(spinnerHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 214, -1, -1));
        add(spinnerMinuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 214, -1, -1));

        jLabel4.setText("min");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 217, -1, -1));

        jLabel5.setText("hr");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 217, -1, -1));

        btnContinuar.setText("Continuar");
        add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 271, -1, -1));

        btnRegresar.setText("jButton2");
        add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 271, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSpinner spinnerHora;
    private javax.swing.JSpinner spinnerMinuto;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
