/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

import ControlNavegacion.ControlNavegacion;

/**
 *
 * @author HP
 */
public class PanelRegistroID extends javax.swing.JPanel {
    private ControlNavegacion control;
    /**
     * Creates new form PanelRegistroID
     */
    public PanelRegistroID(ControlNavegacion control) {
        this.control = control;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelID = new javax.swing.JLabel();
        BtnConfirmar = new javax.swing.JButton();
        CampoId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        CampoPassword = new javax.swing.JPasswordField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelTitulo.setText("¡Bienvenido!");
        add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 210, 91));

        labelID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelID.setText("Ingrese su ID");
        add(labelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 120, 40));

        BtnConfirmar.setBackground(new java.awt.Color(153, 204, 255));
        BtnConfirmar.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        BtnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        BtnConfirmar.setText("Continuar");
        BtnConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnConfirmarMouseClicked(evt);
            }
        });
        add(BtnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 80, -1));
        add(CampoId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 160, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Ingrese su contraseña");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));
        add(CampoPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 252, 160, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnConfirmarMouseClicked
        // TODO add your handling code here:
        System.out.println("ID que va a control    :" + CampoId.getText());
        System.out.println("Password que va a control    :" + CampoPassword.getText());
        
        if(control.validarCredenciales(CampoId.getText(),CampoPassword.getText())){
            //como la implementacion de control.validarCredenciales no esta terminada regresa true
            //esto manda directamente al menu administrador
           control.mostrarPantallaAdminisrador();
        }else{
            //el validarCredenciales regresa false asi que entra el flujo de un estudiante
            // esto se cambiara con las consultas para saber si es estudiante o administrador
            control.mostrarPantallaSeleccionLaboratorio();
        }
        //control.errorCredenciales----- este sera un JOptionPane no se si ponerlo aqui o ya lo cubre el control.validarCredenciales
        //diciendo q las credenciales son incorrectas
    }//GEN-LAST:event_BtnConfirmarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConfirmar;
    private javax.swing.JTextField CampoId;
    private javax.swing.JPasswordField CampoPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
