/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

import ControlNavegacion.ControlNavegacion;

/**
 *
 * @author HP
 */
public class PanelRegistroID extends javax.swing.JPanel {
    private ControlNavegacion control;
    /**
     * Creates new form PanelRegistroID
     */
    public PanelRegistroID(ControlNavegacion control) {
        this.control = control;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelID = new javax.swing.JLabel();
        BtnConfirmar = new javax.swing.JButton();
        CampoId = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelTitulo.setText("¡Bienvenido!");
        add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 210, 91));

        labelID.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelID.setText("Ingrese ID");
        add(labelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        BtnConfirmar.setBackground(new java.awt.Color(0, 0, 0));
        BtnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        BtnConfirmar.setText("Continuar");
        BtnConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnConfirmarMouseClicked(evt);
            }
        });
        add(BtnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 110, 30));
        add(CampoId, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 280, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnConfirmarMouseClicked
        // TODO add your handling code here:
        
        if(control.validarCredenciales(CampoId.getText())){
            //como la implementacion de control.validarCredenciales no esta terminada regresa true
            //control.mostrarPantallaSeleccionLab;
        }
        //control.errorCredenciales----- este sera un JOptionPane 
        //diciendo q las credenciales son incorrectas
    }//GEN-LAST:event_BtnConfirmarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConfirmar;
    private javax.swing.JTextField CampoId;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
